"""
Base model class with common fields (ID, GUID, timestamps)
"""
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, DateTime, func
import uuid

Base = declarative_base()


class BaseModel(Base):
    """
    Base model for all database models with ID, GUID, and timestamps.
    GUID is generated by Python (not DB) for security.
    """
    __abstract__ = True
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    guid = Column(String(36), unique=True, nullable=False, index=True, 
                  default=lambda: str(uuid.uuid4()))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), 
                        onupdate=func.now())
    
    def __repr__(self):
        return f"<{self.__class__.__name__}(id={self.id}, guid={self.guid})>"

